name: Python Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    secrets:
      token:
        required: false
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: run-tests
        run: |
          pytest

      # Step to handle success scenario
      - name: Echo success
        if: ${{ success() }}
        run: echo "All tests passed successfully!"

      # Step to handle failure scenario
      - name: Echo failure
        if: ${{ failure() }}
        run: echo "Some tests failed. Please check the logs for details."
